name: BiomaesteR Build Check and Tests

on:
  pull_request:
    branches: [main]

jobs:
  build-check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::devtools

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Get biocmanager packages
        run: Rscript -e "install.packages('BiocManager')"
        run: Rscript -e "BiocManager::install(c("GenomicRanges","rtracklayer"))"

      - name: Build package
        run: Rscript -e "devtools::install()"

      - name: Check package
        run: Rscript -e "devtools::check(vignettes = FALSE)"

      - name: Run unit tests
        run: Rscript -e "devtools::test()"
    