name: BiomaesteR Build Check and Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    steps:
      - name: Build package
        run:
          Rscript -e "devtools::install()"

      - name: Check package
        run:
          Rscript -e "devtools::check(vignettes = FALSE)"

      - name: Run unit tests
        run: 
          Rscript -e "devtools::test()"
    